# Generated by Django 3.1.5 on 2021-04-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_size', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_toppings', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CreatedPizzas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=250)),
                ('pizza_type', models.CharField(max_length=250)),
                ('pizza_toppings', models.CharField(max_length=500)),
                ('pizza_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.pizzasize')),
            ],
        ),
    ]
