# Generated by Django 3.1.5 on 2021-04-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzasize',
            name='pizza_size',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='pizza_toppings',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
